### ISSUE TITLE
ASCII mode for operating memory window

### ISSUE THREAD

**Issue by pamoroso** [emustudio/emuStudio#210]
**Is your feature request related to a problem? Please describe.**
When a block of memory holds an ASCII string, it's difficult to view it at a glance in the emulator's operating memory window as it displays only the byte values of the individual characters, not the corresponding ASCII characters.

**Describe the solution you'd like**
The operating memory window could provide an ASCII mode to display byte values as the corresponding ASCII characters, e.g. it could display the character `M` at a memory location holding the value `0x4d`.

**Describe alternatives you've considered**
I can't think of any alternatives.

**Additional context**
The proposed ASCII mode may display characters in a way similar to the characters in the right column of the output of the `hexdump -C` Linux program.

**Comment by vbmacher** [comment]
This is perfectly valid request, thank you!

**Comment by pamoroso** [comment]
You're welcome, glad it's a useful suggestion.

**Comment by vbmacher** [comment]
@pamoroso it looks like this now: 
![image](https://user-images.githubusercontent.com/344077/168461010-ec8a3f1d-2c74-41a0-9883-0b2df65b9f39.png)

**Comment by vbmacher** [comment]
Im not an icon designer, I kind of liked the "font" icon from tango scheme, which is used by emuStudio currently

**Comment by pamoroso** [comment]
It looks great, thanks!
