### ISSUE TITLE
Adding END support to the assembler

### ISSUE THREAD

**Issue by pamoroso** [emustudio/emuStudio#211]
**Is your feature request related to a problem? Please describe.**
Many existing Assembly programs terminate with a line containing the `END` directive. Adapting such code to run on emuStudio requires a number of changes, including the removal of `END`.

**Describe the solution you'd like**
Adding `END` support to the assembler would reduce some of the work for porting legacy code to emuStudio.

**Describe alternatives you've considered**
Manually editing code before running it on emuStudio.

**Additional context**
The proposed feature would save a small amount of the work for porting to emuStudio legacy code, which in most cases requires some editing. Therefore, the feature would be worth adding only if the implementation work is limited.

**Comment by vbmacher** [comment]
Hi @pamoroso , how the END directive should behave? Should it ignore all text which comes after it?

**Comment by pamoroso** [comment]
According to the [Intel 8080 Assembly Programming Reference Manual](http://dunfield.classiccmp.org/r/8080asm.pdf) (page 41):

> The END statement signifies to the assembler that the physical end of the program has been reached, and that generation of the object program and (possibly) listing of the source program should now begin.
>
> One and only one END statement must appear in every assembly, and it must be the (physically) last statement of the assembly.

My interpretation is any instructions beyond END should generate an error. But simply ignoring everything after END would be equally acceptable to me.

**Comment by vbmacher** [comment]
@pamoroso this feature has been now implemented, but will be released in version 0.41. You can test it if you want in develop branch. Thanks!
